### ISSUE TITLE
et/et test failures on win32 MSVC x64

### ISSUE THREAD

**Issue by emmenlau** [libevent/libevent#750]
After reporting the regression test failues on MacOSX I checked more carefully the build on MSVC 2017. In the verify-step, there are also a few regression tests are failing. The verify report is here at https://pastebin.com/XPA2nYKA.

Two of the errors seem to be timeouts. Could this be caused by running a debug build? Is this a bug or should I just increase the timeout?

Thanks a lot for your help!

**Comment by azat** [comment]
>   FAIL D:\gitlabci\local\builds\debc216b\0\libevent\test\regress_et.c:124: assert(called == 2): 0 vs 2[msg] libevent using: win32
>  
>  [et FAILED]

This one does not looks like timeout to me, I saw this already (and fails periodically on appveyor ci), but I didn't have time to dig into it.

**Comment by azat** [comment]
> Could this be caused by running a debug build?

Should not

>  Is this a bug or should I just increase the timeout?

Does it **always** fails for you?

**Comment by emmenlau** [comment]
> Does it always fail for you?

It always fails for me, on MSVC 2015 and MSVC 2017.

**Comment by azat** [comment]
Which windows version do you have?

**Comment by emmenlau** [comment]
Its Windows 7 x64, running inside a VirtualBox VM on Ubuntu 18.04.

**Comment by emmenlau** [comment]
I have some specific compiler flags, could that make a difference? The following variables get passed to the cmake configuration:
```
CPPFLAGS="/DDEBUG /DWINVER=_WIN32_WINNT_WIN7 /D_WIN32_WINNT=_WIN32_WINNT_WIN7"
CFLAGS="/MDd /Zi"
CXXFLAGS="/MDd /Zi"
LDFLAGS="/MACHINE:X64 /DEBUG"
```

**Comment by azat** [comment]
> Its Windows 7 x64

Hm, looks like from some point libevent have been testing only on:
- [win8.1](https://ci.appveyor.com/project/nmathewson/libevent/build/job/svje69slbrtyuopd#L70) [MSVC 2015](https://github.com/libevent/libevent/blob/master/appveyor.yml#L3)
- [win10](https://github.com/libevent/libevent-extras/blob/57f806a2ef40823130735bd54ceb0e0e04f75bca/Vagrantfile#L330) [MSVC2013](https://github.com/libevent/libevent-extras/blob/57f806a2ef40823130735bd54ceb0e0e04f75bca/Vagrantfile#L337)

**Comment by azat** [comment]
And AFAICR I tried x64 with MSVC 2017 (144f1b40ef600be41298edf42f48588d0af1d355) and there were some failures

**Comment by azat** [comment]
And that [build](https://ci.appveyor.com/project/azat/libevent/builds/20534946/job/rf5ckte1oeq6g86d#L1546) has exactly the same failure for [x64](https://ci.appveyor.com/project/azat/libevent/builds/20534946/job/rf5ckte1oeq6g86d?fullLog=true#L62)

> et/et: [forking] [msg] libevent using: win32
> FAIL c:\projects\libevent\test\regress_et.c:124: assert(called == 2): 0 vs 2
>  [et FAILED]

**Comment by azat** [comment]
Can you run next command on x64 and x86, plus with and without applying referenced patch?

`EVENT_DEBUG_LOGGING_ALL=1 regress --verbose --no-fork et/et`

**Comment by emmenlau** [comment]
With this change there are a few new errors, but the results are mostly the same. New errors are:
```
main/persistent_active_timeout: [forking] 
  FAIL D:\gitlabci\local\builds\debc216b\0\libevent\test\regress.c:704: assert(labs(timeval_msec_diff(((&start)), ((&res.tvs[2]))) - (500)) <= 50): 60 vs 50[msg] libevent using: win32

  [persistent_active_timeout FAILED]

  [RETRYING persistent_active_timeout (3)]
main/persistent_active_timeout: [forking] 
  FAIL D:\gitlabci\local\builds\debc216b\0\libevent\test\regress.c:704: assert(labs(timeval_msec_diff(((&start)), ((&res.tvs[2]))) - (500)) <= 50): 68 vs 50[msg] libevent using: win32

  [persistent_active_timeout FAILED]

  [RETRYING persistent_active_timeout (2)]
main/persistent_active_timeout: [forking] 
  FAIL D:\gitlabci\local\builds\debc216b\0\libevent\test\regress.c:704: assert(labs(timeval_msec_diff(((&start)), ((&res.tvs[2]))) - (500)) <= 50): 67 vs 50[msg] libevent using: win32

  [persistent_active_timeout FAILED]

  [RETRYING persistent_active_timeout (1)]
main/persistent_active_timeout: [forking] 
  FAIL D:\gitlabci\local\builds\debc216b\0\libevent\test\regress.c:704: assert(labs(timeval_msec_diff(((&start)), ((&res.tvs[2]))) - (500)) <= 50): 75 vs 50[msg] libevent using: win32

  [persistent_active_timeout FAILED]

  [RETRYING persistent_active_timeout (0)]
main/priorities: [forking] [msg] libevent using: win32
OK
main/priority_active_inversion: [forking] [msg] libevent using: win32
OK
main/common_timeout: [forking] 
  FAIL D:\gitlabci\local\builds\debc216b\0\libevent\test\regress.c:800: assert(labs(timeval_msec_diff(((&start)), ((&info[i].called_at))) - (800)) <= 50): 84 vs 50[msg] libevent using: win32

  [common_timeout FAILED]
```

**Comment by emmenlau** [comment]
I just added your patch and rebuild and re-run all tests. The result was identical except the lines shown above. Was that correct? I'm not sure how I can run `EVENT_DEBUG_LOGGING_ALL=1 regress --verbose --no-fork et/et` in the continuous integration system as I don't have direct shell access.

**Comment by azat** [comment]
So you can't add arguments/environment for the executable?

**Comment by azat** [comment]
The problem here is that `EVENT_DEBUG_LOGGING_ALL` will add tons of logs, but strictly speaking just set it for and rerun all tests should work (though very sub optimal).

Doh, I see what the problem is, I messed up while rebasing the patch (from vm), will get back with the fix

**Comment by azat** [comment]
I've just pushed the fix into upstream, `et/*` tests should pass right now.
Thanks!

**Comment by emmenlau** [comment]
Dear @azat, I'm so super sorry about this but I still have the same tests failing. I will start the tests with `EVENT_DEBUG_LOGGING_ALL` now and send you the logs.

**Comment by emmenlau** [comment]
Ok, Ihave tried adding `set EVENT_DEBUG_LOGGING_ALL=1` directly to `tmp/verify_tests.bat` from `CMakeLists.txt`, so all my tests should have it. But the tests are still not more verbose! Maybe CTest is hiding the output? But I also have `export CTEST_OUTPUT_ON_FAILURE=1` thats why the failing tests output should be show on stdout.

Basically I'm now at the end of my wit. How can I help debug the problem?

**Comment by azat** [comment]
Hm, like [I said](https://github.com/libevent/libevent/issues/750#issuecomment-459452909), I don't see any problem *with this test* in your log, do you?

**Comment by emmenlau** [comment]
Hmm, maybe I'm confused, but it says `test-ratelim__group_lim Failed`, and is that to be expected? And the timeout is not set by me. I pass timeout 300 sec to CMake but it is not respected :-)

**Comment by azat** [comment]
Failure of the ratelim is false positive (due to timing issues), while we had been investigating the problem with et/et which is not contained in ratelim it is in regress.
So I think we are fine now

As for cmake not respecting your limit, maybe the problem is in how you are installing environment vars?

**Comment by emmenlau** [comment]
I understand now, thanks a lot for all your help!

About the timout, one more question: I'm using now `ctest --verbose --parallel 2 --timeout 36000` so this is much better than `make verify`. But after 10 hours the (parallel two jobs) Windows test is still not finished! Is this expected from a debug build? Should I test release build? How long is your timeout?

My computer is a AMD Ryzen X2700 so its very modern hardware. Windows is in VirtualBox on Linux, but usually I get like ~90% native performance.

**Comment by azat** [comment]
After taking a look at [your logs](https://pastebin.com/T5P3i4JE) it seems that the hanged test is `ssl/bufferevent_wm` (goes right after `ssl/bufferevent_connect_sleep`, and this is the last one that has been printed), this can be true, and recently I pushed the possible fix the upstream (ae9b285d2d7c9b898049072c157d50769d8014ea)

Can you run it again with this patch included? (or just clone the upstream again, to the moment of writing this HEAD is 6dbad0f6)
