### ISSUE TITLE
libevent tests fail on macOS 10.12

### ISSUE THREAD

**Issue by emmenlau** [libevent/libevent#762]
I've successfully built libevent on macOS 10.11 and macOS 10.12 with XCode 8.3.3, but several tests fail for me with the latest git HEAD revision. I have put the test log here: https://pastebin.com/cPaeSkan

The problems seem similar to my previous issue #749 but I do not know why they disappeared for a while and now came back. This debug log is created with verbose output. Anything I can do to help debug this?

**Comment by azat** [comment]
All of them looks time-related, do you have your machine under some load or/and is it VM?

**Comment by emmenlau** [comment]
I am experimenting with a VM for MacOS 10.13, but this is _not_ the machine that was used here. This is a plain hardware Mac Pro with dual-4-core-Xeon and fast SSD. The machine is not very new, but still quite powerful, and there is no other load than libevent. I run libevent verify with two parallel threads, but the machine should handle much higher load. And the problem is 100% reproducible for different times.

**Comment by azat** [comment]
> This is a plain hardware Mac Pro with dual-4-core-Xeon and fast SSD.
> and there is no other load than libevent

Hm, this is way more than necessary, and I must say that it works in my [vm](https://github.com/libevent/libevent-extras/blob/80b9bbfefa7fbaeb0ae5099a919e1c74e48d244b/Vagrantfile#L231) (osx 10.11 with 1024MB of memory), so I need to take a closer look

> for different times

Can you elaborate?

**Comment by emmenlau** [comment]
> > for different times
> 
> Can you elaborate?

Sorry for the confusion, I just mean that the problem is 100% reproducible, every time I execute the test. I mention this to indicate that t the problem is not related to potential other tasks that the Mac Pro might schedule, like nightly backups.

**Comment by azat** [comment]
>just mean that the problem is 100% reproducible,

Great!

So can I ask you to run those tests only with:
- `EVENT_DEBUG_LOGGING_ALL=` env
- `--no-fork --verbose <test_name>` (i.e. `main/event_remove_timeout`)
- or/and under dtruss (although not sure that I need that verbosity right now)

So for example:
```shell
#!/usr/bin/env bash

tests=(
main/event_remove_timeout
main/persistent_timeout_jump
)
for t in "${tests[@]}"; do
  EVENT_DEBUG_LOGGING_ALL= regress --no-fork --verbose $t
  # EVENT_DEBUG_LOGGING_ALL= sudo --preserve-env dtruss regress --no-fork --verbose $t
done
```

**Comment by emmenlau** [comment]
I understand, thanks for the detailed explanation!

So I did as you suggest. But things get very confusing now. When I execute the tests from the shell (either one by one, as you suggested, or just all tests with `ctest --verbose`, then most tests work successfully! There are still three tests that fail reproducible. These are from `regress__KQUEUE` and `regress__KQUEUE_debug`:
```
  [immediatesignal FAILED]
  [signal_switchbase FAILED]
  [signal_while_processing FAILED]
```

I'm not certain why more tests may fail from my CI system, because I use the same user account, same shell, and same `ctest` executable. The CI works with gitlab runner (see https://docs.gitlab.com/runner/) which is a Go executable. Do you know if this may mess up the environment of libevent?

Here is the debug log of the three failing tests:
```
#> for t in immediatesignal signal_switchbase signal_while_processing ; do EVENT_DEBUG_LOGGING_ALL= ./regress --no-fork --verbose "signal/$t" ; done
signal/immediatesignal: 
  FAIL /data/Debug/libevent/test/regress_main.c:336: Legacy unit test failed
  [immediatesignal FAILED]
1/1 TESTS FAILED. (0 skipped)
signal/signal_switchbase: 
  	 OK /data/Debug/libevent/test/regress.c:1236: assert(event_get_base(&ev1) == base1): 0x7f8501402910 vs 0x7f8501402910
  	 OK /data/Debug/libevent/test/regress.c:1237: assert(event_get_base(&ev2) == base2): 0x7f8501402ba0 vs 0x7f8501402ba0
  FAIL /data/Debug/libevent/test/regress_main.c:336: Legacy unit test failed
  [signal_switchbase FAILED]
1/1 TESTS FAILED. (0 skipped)
signal/signal_while_processing: 
  FAIL /data/Debug/libevent/test/regress_main.c:336: Legacy unit test failed
  [signal_while_processing FAILED]
1/1 TESTS FAILED. (0 skipped)
```

**Comment by azat** [comment]
> So I did as you suggest. But things get very confusing now. When I execute the tests from the shell (either one by one, as you suggested, or just all tests with `ctest --verbose`, then most tests work successfully! There are still three tests that fail reproducible. These are from `regress__KQUEUE` and `regress__KQUEUE_debug`:
> ```
>   [immediatesignal FAILED]
>   [signal_switchbase FAILED]
>   [signal_while_processing FAILED]
> ```

So this is kqueue, and this is good since this should be default backend
on osx (for example if it was SELECT then you should disable kqueue and
poll for libevent to use SELECT by providing next env variables
EVENT_NOKQUEUE= EVENT_NOPOLL= regress ...)

> I'm not certain why more tests may fail from my CI system, because I use the same user account, same shell, and same `ctest` executable. The CI works with gitlab runner (see https://docs.gitlab.com/runner/) which is a Go executable. Do you know if this may mess up the environment of libevent?

It should not I would say (P.S. I have gitlab CI on my TODO list, but I
do not have free VM's for it).

> Here is the debug log of the three failing tests:
> ```
> #> for t in immediatesignal signal_switchbase signal_while_processing ; do EVENT_DEBUG_LOGGING_ALL= ./regress --no-fork --verbose "signal/$t" ; done

This does not adds more logs, because it seems that you disabled debug
logging (cmake -DEVENT__DISABLE_DEBUG_MODE=ON), can you enable it?

**Comment by azat** [comment]
Should be fixed in 728c5dc11f55b4ba5f518812833eab5a2cc3d550

@emmenlau can you please run tests in osx undre your env one more time?

**Comment by emmenlau** [comment]
Dear @azat thank you for your continuous support, its highly appreciated! I still get errors on MacOSX. Hopefully this time I have managed to compile a good issue report: https://pastebin.com/gsPHNzxn
Does this help? Please let me know if I can improve it or provide something else.

**Comment by azat** [comment]
> https://pastebin.com/gsPHNzxn
> Does this help?

Indeed, thanks!

After a brief look most of the failures looks like time related, look:
>   FAIL /data/Builds/libevent/test/regress.c:2045: assert(labs(timeval_msec_diff(((&tv_start)), ((&tv_end))) - (200)) <= 50): 140 vs 50

(*and others*)

Can you give this run more CPU time? (i.e. if you have vm then give more CPU time or reduce CPU usage on host, also consider switching to non-parallel builds if you use `-j` for running tests)

But anyway we need to fix this one way or another, since this will bring [travis-ci osx](https://travis-ci.org/libevent/libevent/jobs/497865750) builds back (since it also has this issues, but there it is due to limited resources and we cannot affect this).

*P.S. I do not have any background in macos, but AFAICR it has bigger latency (if you compare it to linux), for example gdb starts there for ~hours~ very slow*

**Comment by emmenlau** [comment]
> Can you give this run more CPU time? (i.e. if you have vm then give more CPU time or reduce CPU usage on host, also consider switching to non-parallel builds if you use `-j` for running tests)

Actually I think there is not more I can do. This build fails again on the real physical Mac Pro (Dual Xeon 4-Core) machine. The Machine should not have any other load because I never run builds parallel, and the tests where executed with `ctest --parallel 1`. The full test stopped after 16 minutes whereas the allowed limit is 1hr test duration.

**Comment by ploxiln** [comment]
it's possible that some unusual driver is causing huge process/thread scheduling latency

**Comment by azat** [comment]
@emmenlau 
>  This build fails again on the real physical Mac Pro (Dual Xeon 4-Core) machine. The Machine should not have any other load because I never run builds parallel, and the tests where executed with `ctest --parallel 1`.

This is way more than regress tests needs.

Okay, like I said I will take a look into this on weekends, in the mean time can you try run failed tests separately (just pass full test name to the `regress` binary as argument), I assume that they will pass?

@ploxiln 
> it's possible that some unusual driver is causing huge process/thread scheduling latency/jitter

I still think that the problem is the latency issues in macos:

> 
_P.S. I do not have any background in macos, but AFAICR it has bigger latency (if you compare it to linux), for example gdb starts there for hours very slow_

**Comment by ploxiln** [comment]
> I do not have any background in macos, but AFAICR it has bigger latency (if you compare it to linux)

Agreed - it can be pretty different. macOS can have a more responsive UI, because it prioritizes that. But it definitely spawns new processes and threads a lot slower. And I think recent versions are tuned with the assumption that all machines have a fast SSD for the swapfile (and macOS tends to use more memory).
