### ISSUE TITLE
timeout when reading data from socket over SSL

### ISSUE THREAD

**Issue by t7ko** [libevent/libevent#854]
I use libevent to accept incoming HTTPS connections.  What I observe is, sometimes it gets stuck while receiving incoming request body -- as if client did not send small remaining part of the request, and eventually times out.  But right after I send back error response on that socket, event dispatch suddenly discovers that the data is there (event_active with EV_READ on the same socket fd).

After digging a little bit more I have confirmed the following:

Request body is read in portions.  Portions size is equal to high-water mark value.  Which means the last portion will be smaller -- in my case high-water mark = 16k, and last portion is 576 bytes.  So what happens is, when it has extracted last whole 16k portion from SSL context (with SSL_read), the remaining 576 bytes are already extracted from the underlying socket and stored in SSL context.  I have confirmed this by adding debug printout and a call to SSL_pending -- it returns 576 bytes.  But since high-water mark is reached, it sets bev.read_suspended flag to true, and exits from consider_reading, and does not even check for SSL_pending.  This exit happens at `if (bev_ssl->bev.read_suspended) break;`  (see [here, in code](https://github.com/libevent/libevent/blob/release-2.0.22-stable/bufferevent_openssl.c#L789-L790)), which is before the code which is supposed to handle this "pending" issue.  After that, after read iteration is completed, libevent calls add_event for ev_read for the underlying fd of the socket.  And since all data is already extracted from that socket and stored in SSL buffers -- that event is never triggered.  And it eventually times out.

I am using libevent 2.0.22.  Cannot update to latest due to dependencies.  Unfortunately I don't have a procedure to reproduce this in some simple test app -- I could only reproduce this as part of system test of my app with many other components.  But I briefly checked latest code and I don't see any fixes neither in start_reading nor in consider_reading.

I came up with a very simple fix.  It seems to be obvious, and so I'm very suspicious that no one has implemented it before.  Please let me know if it makes sense?

The fix is in `bufferevent_openssl.c`, `start_reading` function.  Right after it adds event for reading, below this line:

```
		r = bufferevent_add_event_(&bev->ev_read, &bev->timeout_read);
```

(see [here, in code](https://github.com/libevent/libevent/blob/release-2.0.22-stable/bufferevent_openssl.c#L385))

I add the following:

```
    if (SSL_pending(bev_ssl->ssl) > 0)
          evmap_io_active(bev->ev_base, bev->ev_read.ev_fd, EV_READ | EV_ET);
```

Please let me know if this is proper fix, and I can create PR then, -- or maybe I'm missing something here.

**Comment by azat** [comment]
>Portions size is equal to high-water mark value

So you are using watermarks over openssl buffer

> But since high-water mark is reached, it sets bev.read_suspended flag to true, and exits from consider_reading, and does not even check for SSL_pending

Looks like the following patch in upstream should fix it 5a455acd3bdf9a0117f909450ac7ea693ca93912, I read that you cannot migrate from libevent 2.0, but if you can just check last upstream onetime that will be great? If not you can backport that patch to **2.0.23** (note 2.0.23 here, not 2.0.22) (I just verified that it applies cleanly without any conflicts).

>I am using libevent 2.0.22

Unfortunately 2.0.x is not supported already, but there will be at least one stable release (since the last one is 2.0.23-beta and we need at least one -stable after), so the great news for your that next 2.0.x -stable will come.

**Comment by azat** [comment]
@t7ko any news here?

**Comment by QbsuranAlang** [comment]
The issue is still there in 2.1.11-stable.

My situation is:
First use a bufferevent(not a SSL filter) on a socket, the connection is established and client is sent a "Client Hello". I only detect "read event" that let me know client sent something, then do another function. When done, I allocated a SSL filter bufferevent with `bufferevent_openssl_filter_new()` to handle client SSL accept event.

But here is wire thing happened. It sometimes triggers read event, but sometimes it won't. I don't deep study the source code. I added the following code @t7ko said to latest version source:

```
...
#include "event-internal.h"
#include "evmap-internal.h"
...
    if (SSL_pending(bev_ssl->ssl) > 0)
          evmap_io_active_(bev->ev_base, bev->ev_read.ev_fd, EV_READ | EV_ET);
```

and everything is works fine.

**Comment by smirn0v** [comment]
Got the same issue. Is there any approved fix ?
